'use strict';

const assert = require('assert');
const sinon = require('sinon');
const Database = require('../db');
const id = require('../utils/id');
const userController = require('./user');

describe('controllers/user', function() {
  afterEach(function() {
    sinon.restore();
  })
  
  describe('#createUser()',  function() {
    it('should call db query', async function() {
      let dbQueryStub = sinon.stub(Database.prototype, 'query');
      dbQueryStub.resolves('success');
      let result = await userController.createUser('test_email', 'test_password', 'test_first_name', 'test_last_name');
      assert(dbQueryStub.calledOnce);
      assert.equal(result, 'success');
    });

    it('should create a user with id generated by util/id.genUserId', async function () {
      let dbQueryStub = sinon.stub(Database.prototype, 'query');
      dbQueryStub.resolves('success');
      sinon.stub(id, 'genUserId').returns('test_user_id');
      await userController.createUser('test_email', 'test_password', 'test_first_name', 'test_last_name');

      sinon.assert.calledWith(dbQueryStub,
        'INSERT INTO Users VALUES (?, ?, ?, ?, ?)',
        [
          'test_user_id',
          'test_email',
          'test_first_name',
          'test_last_name',
          'test_password'
        ]
      );
    });

    it('should throw error with message "Fail to insert into database" if db.query fails', async function () {
      let dbQueryStub = sinon.stub(Database.prototype, 'query');
      dbQueryStub.rejects('failure');
      try {
        await userController.createUser('test_email', 'test_password', 'test_first_name', 'test_last_name');
        assert(false, 'error should have been thrown');
      } catch (e) {
        assert(dbQueryStub.calledOnce);
        assert.equal(e.message, "database_error");
      }
    });
  });

  describe('#login()', function() {
    it('should call db query', function() {

    });
  })
});